name: BuildAndPackage

on:
  push:
  pull_request:
    branches: 
    - main

jobs:
  build-and-package:
    name: Build and Package
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest]
    #  framework: [ 'netcoreapp3.1', 'netcoreapp2.1']

    steps:
    - name: Check out code from repository
      uses: actions/checkout@v2

    - name: Cleanup Package Cache
      run: |
        cd ./src/SingPassAuthentication
        dotnet clean SingPassAuthentication.sln
        dotnet nuget locals all --clear

    - name: Build and Package
      run: |
        cd ./src/SingPassAuthentication
        dotnet restore
        dotnet build --no-restore      

    - name: Upload Package 
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/SingPassAuthentication/SingPassAuthentication/bin/Release/*.nupkg
       
